[package]
name = "car-drive"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.1"
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = "0.1.17"
tokio-tungstenite = "0.26.2"
futures = "0.3.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
downstream-rs = { path = "../../crates/downstream-rs" }
